jobs:
  GenerateYAML:
    docker:
      - image: cimg/base:2020.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=$CIRCLE_WORKFLOW_ID
          git clone https://$GITHUB_AUTH@github.com/AnimaApp/anima-argocd /tmp/CircleCI-Webapp-CD
          cd /tmp/CircleCI-Webapp-CD
          cp /tmp/CircleCI-Webapp-CD/anima-cluster/default/deployments.yaml .
          sed -i 's/\(anima-api:\)\(.*\)/\1'$TAG'/' ./anima-cluster/default/deployments.yaml
          rm deployments.yaml
          git config credential.helper 'cache --timeout=120'
          git config user.email $GIT_AUTH_EMAIL
          git config user.name $GIT_AUTH_USERNAME
          git add .
          git commit -m ${GIT_COMMIT_DESC}
          # Push quietly to prevent showing the token in log
          git push -q https://$GITHUB_AUTH@github.com/AnimaApp/anima-argocd.git main


workflows:
  version: 2
  Test-Build-Publish:
    jobs:
      - GenerateYAML

