jobs:
  GenerateYAML:
    docker:
      - image: cimg/base:2020.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/AnimaApp/anima-gke-argocd /tmp/CircleCI-Webapp-CD
          cd /tmp/CircleCI-Webapp-CD
          cp /tmp/CircleCI-Webapp-CD/anima-cluster/default/deployments.yaml .
          sed -i 's/\(anima-api:\)\(.*\)/\1'$TAG'/' ./anima-cluster/default/deployments.yaml
          git config credential.helper 'cache --timeout=120'
          git config user.email "lekeariyo2015@gmail.com"
          git config user.name "leke-ariyo"
          git add .
          #git commit -m "Updated image tag via CircleCI"
          git commit -m ${GIT_COMMIT_DESC}
          # Push quietly to prevent showing the token in log
          #git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/AnimaApp/anima-gke-argocd.git main



workflows:
  version: 2
  Test-Build-Publish:
    jobs:
      - GenerateYAML

